
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: zabbix-sre-dev:latest
    container_name: zabbix-sre-dev
    env_file:
      - .env
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      PORT: "${PORT:-5000}"
    ports:
      - "${PORT:-5000}:5000"
      # Porta de debugpy (se usar)
      # - "5678:5678"
    volumes:
      - .:/app:delegated
      # Evitar que o venv do host colida:
      # - /app/.venv
    restart: unless-stopped
